### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by JSDforJ** [Hypejet/Jet#8]
Jet should support SpongeMixins, might be complicated as we need to have a class transformer or something, however there are already libraries doing this and fabric has a pretty full library doing this too.

**Comment by Codestech1** [comment]
Do mixins even make sense in server software like Jet? Jet does not aim to contain behaviour to modify like in Minecraft code.

**Comment by JSDforJ** [comment]
Mixins isnt just for minecraft, here it can be used to modify the codw of jet

**Comment by Codestech1** [comment]
> Mixins isnt just for minecraft, here it can be used to modify the codw of jet

Yeah, i know, But what would be a use-case in Jet? Our software do not contain features - like in Minecraft - that a user would like to modify, except of fixes and improvements, which are done via pull requests.

**Comment by JSDforJ** [comment]
There might be something really specific the user wants to change, it would generally be useful for things you would normally  make a fork for, its just easier to do it with mixins.

**Comment by Codestech1** [comment]
Adding this to a roadmap, with a low priority, because there are more important features to implement in Jet.

**Comment by JSDforJ** [comment]
Yup

**Comment by Codestech1** [comment]
It's not a planned feature of Jet. Our server software can be customized in an easier way via plugins, you'll see.
